library(xcms)
cdffiles=c("C:/Users/Marco/Documents/R/win-library/2.10/faahKO/cdf/KO/ko15.CDF","C:/Users/Marco/Documents/R/win-library/2.10/faahKO/cdf/KO/ko16.CDF","C:/Users/Marco/Documents/R/win-library/2.10/faahKO/cdf/KO/ko18.CDF","C:/Users/Marco/Documents/R/win-library/2.10/faahKO/cdf/KO/ko19.CDF","C:/Users/Marco/Documents/R/win-library/2.10/faahKO/cdf/KO/ko21.CDF","C:/Users/Marco/Documents/R/win-library/2.10/faahKO/cdf/KO/ko22.CDF")
xset<-xcmsSet(cdffiles, method="centWave", ppm=10, scanrange=c(300.0,3200.0), snthresh=10, peakwidth=c(15.0,30.0), noise=1000, fitgauss=TRUE, integrate=1, mzdiff=0.25)
xsetgp1<-group(xset, minfrac=0.8, sleep=0, bw=5, max=50, mzwid=0.02)
xsetrt<-retcor(xsetgp1, method="obiwarp")
xsetgp2<-group(xsetrt,  minfrac=0.8, sleep=0, bw=5, max=50, mzwid=0.02)
xset3 <-fillPeaks(xsetgp2)
write.table(peaks(xset3), paste("peaks.pkl"), sep=";")
q()